name: Dart and Flutter CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Dart SDK
      - uses: dart-lang/setup-dart@latest

      # Install Dart dependencies
      - name: Install dependencies
        run: dart pub get

      # Analyze Dart source code
      - name: Analyze project source
        run: dart analyze

      # Run Dart tests
      - name: Run Dart tests
        run: dart test

      # Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.2  # Adjust version as needed

      # Install Flutter dependencies
      - run: flutter pub get

      # Run Flutter tests
      - run: flutter test
